routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DonateController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\LoginController;
use App\Http\Controllers\Frontend\SocialController;
use App\Http\Controllers\Frontend\CompareController;
use App\Http\Controllers\Frontend\RegisterController;
use App\Http\Controllers\Frontend\WishlistController;
use App\Http\Controllers\Frontend\Cart\CartController;
use App\Http\Controllers\Frontend\NewsLetterController;
use App\Http\Controllers\Frontend\Product\DetailController;
use App\Http\Controllers\Frontend\Product\CategoryController;
use App\Http\Controllers\Frontend\VerifyCustomerEmailController;

Route::prefix('')->group(function(){
    Route::get('home', [HomeController::class, 'index'])->name('home.index');
    Route::get('show-modal/{id}', [HomeController::class, 'show'])->name('home.show');
    Route::get('wishlist', [wishlistController::class, 'index'])->name('wishlist.index');

    // Customer
    Route::post('register-customer', [RegisterController::class, 'register'])->name('register-customer');
    Route::post('login-customer', [LoginController::class, 'login'])->name('login-customer');
    // Social
    Route::controller(SocialController::class)->group(function () {
        Route::get('auth/{provider}', 'redirectToSocial')->name('auth.social');
        Route::get('auth/{provider}/callback', 'handleSocialCallback');
    });

    // Email verification
    Route::get('verify-email/{id}/{token}', [VerifyCustomerEmailController::class, 'verify'])
                                            ->middleware(['throttle:6,1'])
                                            ->name('verify-email.customer');
    // Cart
    Route::get('cart/{id}', [CartController::class, 'cart'])->name('cart');
    Route::get('add-to-cart/{id}', [CartController::class, 'addToCart'])->name('add.to.cart');
    Route::patch('update-cart', [CartController::class, 'update'])->name('update.cart');
    Route::delete('remove-from-cart', [CartController::class, 'removeCart'])->name('remove.from.cart');
    // End cart

    // wishlist
    Route::get('wishlist/{id}', [CartController::class, 'wishlist'])->name('wishlist');
    Route::get('add-to-wishlist/{id}', [CartController::class, 'addToWishlist'])->name('add.to.wishlist');
    Route::delete('remove-from-wishlist', [CartController::class, 'removeWishlist'])->name('remove.from.wishlist');
    // End wishlist
    Route::delete('remove-product-to-compare', [CompareController::class, 'removeProdToCompare'])->name('remove.from.product_to_compare');
    // Product to compare

    // End product to compare
    // Product Category
    Route::get('product-categories/{productCategory}', [CategoryController::class, 'show'])->name('product-category.show');
    // End Product Category

    // Product Detail
    Route::get('product-detail/{productDetail}', [DetailController::class, 'show'])->name('product-detail.show');
    // End Product Detail

    // send join us
    Route::post('/subscribe', [NewsLetterController::class, 'subscribe'])->name('subscribe');

    // compare
    Route::get('/compare', [CompareController::class, 'index'])->name('compare.index');
    Route::post('/compare-post', [CompareController::class, 'postCompare'])->name('compare.post');
    Route::get('/compare-get', [CompareController::class, 'getCompare'])->name('compare.get');

    // VN Pay
    Route::post('/donate-create', [DonateController::class, 'create'])->name('donate.create');
    Route::get('/donate-vnpay', [DonateController::class, 'index'])->name('donate.vnpay.index');
    Route::get('/vnpay_php/vnpay_return', [DonateController::class, 'return'])->name('return.index');

    Route::post('/transaction', [DonateController::class, 'transaction'])->name('transaction.post');
    Route::post('/refund', [DonateController::class, 'refund'])->name('refund.post');
    // Momo

    Route::get('/atm-momo', [DonateController::class, 'atm_momo'])->name('donate.momo.index');
    Route::get('/result-atm', [DonateController::class, 'result_atm'])->name('donate.result.index');

    // filter price
    Route::post('/arrange-price', [CategoryController::class, 'arrangePrice'])->name('arrange.price');
    // logout
    Route::get('/logout', [HomeController::class, 'logout'])->name('logout.customer');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\LoginController;
use App\Http\Controllers\Backend\SlackController;
use App\Http\Controllers\Backend\DonateController;
use App\Http\Controllers\Frontend\SearchController;
use App\Http\Controllers\Backend\CustomerController;
use App\Http\Controllers\Backend\DiscountController;
use App\Http\Controllers\Backend\RegisterController;
use App\Http\Controllers\Backend\Users\UserController;
use App\Http\Controllers\Backend\NotificationSendController;
use App\Http\Controllers\Backend\Products\ProductController;
use App\Http\Controllers\Backend\Email\VerifyEmailController;
use App\Http\Controllers\Backend\Users\UserProfileController;
use App\Http\Controllers\Backend\Password\NewPasswordController;
use App\Http\Controllers\Backend\Products\ProductCategoryController;
use App\Http\Controllers\Backend\Password\PasswordResetLinkController;
use App\Http\Controllers\Backend\Password\ConfirmablePasswordController;
use App\Http\Controllers\Backend\Email\EmailVerificationPromptController;
use App\Http\Controllers\Backend\Email\EmailVerificationNotificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Authentication Routes...
Route::prefix('admin')->name('admin.')->group(function(){
    Route::middleware('guest')->group(function () {
        // Start Login
        Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
        Route::post('login', [LoginController::class, 'login'])->name('login.post');
        // End Login
        // Start Register
        Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
        Route::post('register', [RegisterController::class, 'create'])->name('register.post');
        // End Register
        });
        // End Password Confirm
    Route::middleware('auth')->group(function(){
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
        // Users
        Route::resource('users', UserController::class);
        Route::get('user_profile', [UserProfileController::class, 'index'])->name('user_profile.index');
        Route::get('user_profile/edit/{user}', [UserProfileController::class, 'edit'])->name('user_profile.edit');
        // Roles
        Route::resource('roles', RoleController::class);
        // Products
        Route::resource('products', ProductController::class);
        // Customers
        Route::resource('customers', CustomerController::class);
        // Product Categories
        Route::resource('product_category', ProductCategoryController::class);
        // Donate
        Route::get('donates', [DonateController::class, 'index'])->name('donates.index');
        Route::get('donate-edit', [DonateController::class, 'edit'])->name('donates.edit');
        //Coupon
        Route::get('coupon', [DiscountController::class, 'index'])->name('coupon.index');
        // notice
        Route::get('/notice', [NotificationSendController::class, 'index'])->name('notice.index');
        Route::post('/store-token', [NotificationSendController::class, 'updateDeviceToken'])->name('store.token');
        Route::post('/send-web-notification', [NotificationSendController::class, 'sendNotification'])->name('send.web-notification');
        //Logout
        Route::get('/logout', [DashboardController::class, 'destroy'])->name('logout');
    });
});
Route::prefix('admin')->group(function(){
    // Email
    Route::get('verify-email', [EmailVerificationPromptController::class, '__invoke'])
    ->name('verification.notice');

    Route::get('verify-email/{id}/{hash}', [VerifyEmailController::class, '__invoke'])
    ->middleware(['signed', 'throttle:6,1'])
    ->name('verification.verify');

    Route::post('email/verification-notification', [EmailVerificationNotificationController::class, 'store'])
            ->middleware('throttle:6,1')
            ->name('verification.send');
    // End Email
    // Password
    Route::get('forgot-password', [PasswordResetLinkController::class, 'create'])
    ->middleware('guest')
    ->name('password.request');

    Route::post('forgot-password', [PasswordResetLinkController::class, 'store'])
    ->middleware('guest')
    ->name('password.email');

    Route::get('reset-password/{token}', [NewPasswordController::class, 'create'])
    ->middleware('guest')
    ->name('password.reset');

    Route::post('reset-password', [NewPasswordController::class, 'store'])
    ->middleware('guest')
    ->name('password.update');

    // Password Confirm
    Route::get('confirm-password', [ConfirmablePasswordController::class, 'show'])
            ->name('password.confirm');

    Route::post('confirm-password', [ConfirmablePasswordController::class, 'store']);
    // End Password

    Route::get('send', [DashboardController::class, 'send'])->name('home.send');

    // Search
    Route::post('search/name', [SearchController::class, 'getSearchAjax'])->name('search');

    // Notification Slack
    Route::get('slack', [SlackController::class,'slack'])->name('slack');

    // Impersonate
    Route::get('/{user}/impersonate', [UserController::class, 'impersonate'])->name('users.impersonate');
    Route::get('/leave-impersonate', [UserController::class, 'leaveImpersonate'])->name('users.leave-impersonate');

});

resources/views/site/pages/notice.blade.php
@extends('site.layouts.master')
@section('title'){{'Yêu thích'}}@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
                <button onclick="startFCM()"
                    class="btn btn-danger btn-flat">Allow notification
                </button>
            <div class="card mt-3">
                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    <form action="{{ route('admin.send.web-notification') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label>Tiêu đề</label>
                            <input type="text" class="form-control" name="title">
                        </div>
                        <div class="form-group">
                            <label>Nội dung</label>
                            <textarea class="form-control" name="body"></textarea>
                        </div>
                        <button type="submit" class="btn btn-success btn-block">Send Notification</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- The core Firebase JS SDK is always required and must be listed first -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.3.2/firebase.js"></script>
<script>
    var firebaseConfig = {
        apiKey: "AIzaSyCjS2xW6NRDub37CtmzPR7z--fqraxfLjQ",
        authDomain: "graduation-thesis-79e40.firebaseapp.com",
        projectId: "graduation-thesis-79e40",
        storageBucket: "graduation-thesis-79e40.appspot.com",
        messagingSenderId: "511960949605",
        appId: "1:511960949605:web:b89277969a6330e0c9f78c",
        measurementId: "G-NMRQE2D7N6"
    };
    firebase.initializeApp(firebaseConfig);
    const messaging = firebase.messaging();
    function startFCM() {
        messaging
            .requestPermission()
            .then(function () {
                return messaging.getToken()
            })
            .then(function (response) {
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                $.ajax({
                    url: '{{ route("admin.store.token") }}',
                    type: 'POST',
                    data: {
                        _token: '{{ csrf_token() }}',
                    },
                    dataType: 'JSON',
                    cache : false,
                    success: function (response) {
                        alert('Token stored.');
                    },
                    error: function (error) {
                        alert(error);
                    },
                });
            }).catch(function (error) {
                alert(error);
            });
    }
    messaging.onMessage(function (payload) {
        const title = payload.notification.title;
        const options = {
            body: payload.notification.body,
            icon: payload.notification.icon,
        };
        new Notification(title, options);
    });
</script>
@endsection